"""empty message

Revision ID: 197cc8721887
Revises: 4e2f94c2292c
Create Date: 2014-12-13 00:59:46.549408

"""

# revision identifiers, used by Alembic.
revision = '197cc8721887'
down_revision = '4e2f94c2292c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device')
    ### end Alembic commands ###
