"""empty message

Revision ID: 1ee9a9c3e3da
Revises: 815a6344ac9
Create Date: 2014-11-28 08:46:52.596514

"""

# revision identifiers, used by Alembic.
revision = '1ee9a9c3e3da'
down_revision = '815a6344ac9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=15), nullable=False))
    ### end Alembic commands ###
