"""empty message

Revision ID: 2954e2425d0f
Revises: 3cd78300dede
Create Date: 2014-12-07 16:01:35.158518

"""

# revision identifiers, used by Alembic.
revision = '2954e2425d0f'
down_revision = '3cd78300dede'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_shares', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_column('post_shares', 'post_comment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_shares', sa.Column('post_comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('post_shares', 'post_id')
    ### end Alembic commands ###
