"""empty message

Revision ID: 2f93be9ae6e
Revises: None
Create Date: 2014-11-22 20:46:23.055382

"""

# revision identifiers, used by Alembic.
revision = '2f93be9ae6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=15), nullable=False),
    sa.Column('nickname', sa.Unicode(length=10), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('golds', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.Unicode(length=30), nullable=False),
    sa.Column('push', sa.Boolean(), nullable=False),
    sa.Column('no_disturb', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
