"""empty message

Revision ID: 33ebf6ececea
Revises: 360411cf0b91
Create Date: 2014-12-06 23:19:27.368460

"""

# revision identifiers, used by Alembic.
revision = '33ebf6ececea'
down_revision = '360411cf0b91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###
