"""empty message

Revision ID: 3569be055f4d
Revises: 18259faca3be
Create Date: 2014-12-23 14:46:10.041885

"""

# revision identifiers, used by Alembic.
revision = '3569be055f4d'
down_revision = '18259faca3be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_read')
    ### end Alembic commands ###
