"""empty message

Revision ID: 360411cf0b91
Revises: 125320f524c6
Create Date: 2014-12-02 23:52:17.872868

"""

# revision identifiers, used by Alembic.
revision = '360411cf0b91'
down_revision = '125320f524c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.alter_column('posts', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('posts', 'likes_count')
    ### end Alembic commands ###
