"""empty message

Revision ID: 3b6c523c1b43
Revises: 33ebf6ececea
Create Date: 2014-12-06 23:57:43.267155

"""

# revision identifiers, used by Alembic.
revision = '3b6c523c1b43'
down_revision = '33ebf6ececea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.CHAR(length=64), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post_comment_likes', sa.Column('unified_user_id', sa.Integer(), nullable=False))
    op.drop_column(u'post_comment_likes', 'user_id')
    op.add_column(u'post_likes', sa.Column('unified_user_id', sa.Integer(), nullable=False))
    op.drop_column(u'post_likes', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'post_likes', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column(u'post_likes', 'unified_user_id')
    op.add_column(u'post_comment_likes', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column(u'post_comment_likes', 'unified_user_id')
    op.drop_table('unified_users')
    ### end Alembic commands ###
