"""empty message

Revision ID: 3bf3d6f9cb58
Revises: 197cc8721887
Create Date: 2014-12-14 01:24:18.340488

"""

# revision identifiers, used by Alembic.
revision = '3bf3d6f9cb58'
down_revision = '197cc8721887'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('navbar', sa.String(length=64), nullable=False))
    op.add_column('channels', sa.Column('panel', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'panel')
    op.drop_column('channels', 'navbar')
    ### end Alembic commands ###
