"""empty message

Revision ID: 492dbd796bc
Revises: 2ac8f53cfd0e
Create Date: 2014-11-26 21:51:39.007545

"""

# revision identifiers, used by Alembic.
revision = '492dbd796bc'
down_revision = '2ac8f53cfd0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fans', sa.Column('created', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fans', 'created')
    ### end Alembic commands ###
