"""empty message

Revision ID: 815a6344ac9
Revises: 492dbd796bc
Create Date: 2014-11-26 23:41:38.503536

"""

# revision identifiers, used by Alembic.
revision = '815a6344ac9'
down_revision = '492dbd796bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fans', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fans', 'is_deleted')
    ### end Alembic commands ###
